### PR TITLE
Fixed route builder giving incorrect distance due to viewport limited…

### LINKED ISSUE #3618: RouteBuilder viz & distance calculation incorrect when zoomed in
##### Brief description of problem/feature
In RouteBuilder, it seems like only the currently visible part of the street being selected is being included in the distance calculation and is being shown to be part of the route when you click on it. But if you save the route and Explore, you are sent to the correct street either way. Example below!

##### System info (OS, browser, city, and local/prod/test)
Tested on prod, test, and local. Tested on Chrome and Firefox.

##### Steps to reproduce
First, hover over a long street where you can see the entire street.
Screenshot from 2024-08-19 11-58-45

Click on the street to add it. In this example, the street is 0.93 miles long.
Screenshot from 2024-08-19 11-58-47

Remove the street, then zoom in so that you can only see a fraction of the street.
Screenshot from 2024-08-19 11-59-46

Click on that street to add it. It seems to only add a portion of the street, showing a route length of only 0.25 miles. And only the visible portion of the street visually looks like it's been added. Note that the portion of the street that doesn't look like it's been added is actually in white instead of blue.
Screenshot from 2024-08-19 11-59-51

BUT if you hover your mouse over the part of the street that wasn't included, you can still interact with the street to reverse its direction or remove it.
Screenshot from 2024-08-19 11-59-57

### PR DESCRIPTION
**Pull request by Jetpackjules**
Resolves #3618 

**Problem:** When adding streets to a route while zoomed in, only the visible portion was used to calculate distance rather than the entire street. This led to incorrect visual highlighting and inaccurate distance calculations.

**Solution:** Modified the street selection logic to retrieve and use the complete street geometry from the original data source, creating a deep copy to safely handle direction modifications.

### Before/After screenshots (if applicable)
Before (Upon zoomed-in selection of street):
image

After (Upon zoomed-in selecton of street):
image

##### Testing instructions
1. Navigate to RouteBuilder tool
2. Find suitable long street ( > 0.1m preferred)
3. Note length of street when it is entirely on-screen.
4. Zoom in until portion of street is off-screen and re-select, comparing length.

##### Things to check before submitting the PR 

- [X] I've written a descriptive PR title. 
- [X] I've added/updated comments for large or confusing blocks of code.
- [X] I've included before/after screenshots above.
- [X] I've asked for and included translations for any user facing text that was added or modified.
- [X] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how (or if you need to update the logging), ask Mikey. Then make sure the documentation on [this wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Descriptions-of-Logged-Events) is up to date for the logs you added/updated.
- [X] I've tested on mobile (only needed for validation page).

### CODE REVIEW

File: public/javascripts/routeBuilder.js [hunk 1]
```diff
@@ -430,17 +430,26 @@ function RouteBuilder ($, mapParams) {
             } else { // If the street was not in the route, add it to the route.
                 map.setFeatureState({ source: 'streets', id: hoveredStreet }, { chosen: 'chosen' });
 
-                // Check if we should reverse the street direction to minimize number of contiguous sections.
-                if (shouldReverseStreet(street)) {
-                    street.geometry.coordinates.reverse();
-                    street.properties.reverse = !street.properties.reverse;
+                // Using complete street data from source (To avoid viewport-limited sizes)
+                const fullStreetData = streetData.features.find(s =>
```
Comment (misaugstad) [inline public/javascripts/routeBuilder.js:434]: Is there any reason that we shouldn't do this at the top of the `map.on('click'`, and maybe at the top of our `map.on('mousemove'` too since it also gets the street using `const street = event.features[0];`? This way we know that we'll always have the full geometry?

File: public/javascripts/routeBuilder.js [hunk 2]
```diff
@@ -430,17 +430,26 @@ function RouteBuilder ($, mapParams) {
...
+                    s.properties.street_edge_id === street.properties.street_edge_id
+                );
+
+                // Create a deep copy of the full street data to avoid modifying the original.
+                const fullStreet = JSON.parse(JSON.stringify(fullStreetData));
```
Comment (misaugstad) [inline public/javascripts/routeBuilder.js:439]: Is there a reason that we need to be concerned about making edits to the data right now, or is the deep copy just extra rn?

File: public/javascripts/routeBuilder.js (hunk 1 above)
Comment (misaugstad) [inline public/javascripts/routeBuilder.js:434]: Instead of accessing the underlying data directly, we should probably keep with the Mapboxy way of getting the source data, something like:
```
const fullStreet = map.querySourceFeatures('streets', {
    filter: ['==', ['get', 'street_edge_id'], street.properties.street_edge_id]
})[0];
```

File: public/javascripts/routeBuilder.js [hunk 3]
```diff
@@ -430,17 +430,26 @@ function RouteBuilder ($, mapParams) {
             } else { // If the street was not in the route, add it to the route.
                 map.setFeatureState({ source: 'streets', id: hoveredStreet }, { chosen: 'chosen' });
 
-                // Check if we should reverse the street direction to minimize number of contiguous sections.
-                if (shouldReverseStreet(street)) {
-                    street.geometry.coordinates.reverse();
-                    street.properties.reverse = !street.properties.reverse;
+                // Using complete street data from source (To avoid viewport-limited sizes)
```
Comment (misaugstad) [inline public/javascripts/routeBuilder.js:433]: I feel like this comment only makes sense to us because we know what bug we're fixing right now, but if I looked back at this 6 months from now, I wouldn't have any idea what "viewport-limited sizes" are.

**Review by misaugstad — CHANGES_REQUESTED** [review]
Fix works, there's just some changes we should make to the exact implementation!

**Comment by misaugstad** [comment]
Oh, and a reminder to merge in changes from develop before fully testing and submitting PRs!

File: public/javascripts/routeBuilder.js (hunk 2 above)
Comment (Jetpackjules) [reply public/javascripts/routeBuilder.js:439]: You are right - the deep copy is technically optional. I had added it a precaution to avoid a case where, say, we reverse the street and end up permanently changing the source object, but that does not seem to be a real issue, and was not a concern / creating issues in the original code, so I will scrap it.

File: public/javascripts/routeBuilder.js (hunk 1 above)
Comment (Jetpackjules) [reply public/javascripts/routeBuilder.js:434]: Unfortunately that would not work as it would reintroduce the viewport limitation problem - querySourceFeatures() and mapbox methods in general only return features currently in the viewport or tile cache, which is what led to the bug :(

File: public/javascripts/routeBuilder.js (hunk 3 above)
Comment (Jetpackjules) [reply public/javascripts/routeBuilder.js:433]: Fixed (In the next commit) to mention why the line is necessary in lieu of the prior bugged implementation.

File: public/javascripts/routeBuilder.js (hunk 1 above)
Comment (Jetpackjules) [reply public/javascripts/routeBuilder.js:434]: My initial reasoning was to be as unintrusive as possible on the existing code to avoid any conflicts, and no other parts of the code required complete street data to function - but you are right. it makes more sense to do a few more changes to make it work at the start for uniformity and future-proofing. Added in next commit!

**Review by misaugstad — APPROVED** [review]
Looking good, thanks @Jetpackjules!
