### PR TITLE
2584 shorten labels uri

### LINKED ISSUE #2584: Sidewalk Gallery: Request-URI Too Long
I was on page ~20 when I received this error: "Failed to load resource: the server responded with a status of 414 (Request-URI Too Long)". Full error below:

```
label/labelsBySeveritiesAndTags?labelTypeId=4&n=9&loadedLabels=%5B59055%2C45268%2C81444%2C49598%2C38299%2C22042%2C93464%2C32070%2C96339%2C99173%2C80386%2C94136%2C53920%2C32746%2C73434%2C7061%2C77950%2C51573%2C9380%2C7284%2C24032%2C29340%2C95310%2C58274%2C48877%2C22269%2C65671%2C36488%2C2697%2C74270%2C7462%2C47140%2C56638%2C46767%2C67839%2C44361%2C43033%2C105982%2C34075%2C86400%2C62247%2C36420%2C91153%2C13074%2C89580%2C16236%2C105418%2C97483%2C101396%2C91376%2C98412%2C78438%2C70836%2C66981%2C49456%2C48467%2C16756%2C21223%2C1062%2C106341%2C62427%2C86801%2C82280%2C86373%2C88714%2C87794%2C3634%2C70180%2C9817%2C34189%2C66409%2C1054%2C50635%2C90785%2C89752%2C72264%2C27066%2C27580%2C49661%2C19199%2C90683%2C106343%2C4066%2C13461%2C51861%2C82275%2C34045%2C108400%2C79987%2C45165%2C49446%2C24833%2C75854%2C52573%2C65932%2C18799%2C53250%2C8022%2C33936%2C49699%2C59584%2C16880%2C477%2C98084%2C67117%2C48677%2C70084%2C89710%2C9765%2C23374%2C59493%2C90684%2C53122%2C89507%2C4732%2C99364%2C18751%2C80613%2C68710%2C87672%2C79647%2C77446%2C48887%2C47694%2C33225%2C87370%2C77671%2C90688%2C24961%2C34959%2C33296%2C67607%2C3956%2C76594%2C49968%2C43483%2C90394%2C75357%2C90882%2C34913%2C93421%2C65454%2C43476%2C79881%2C37816%2C37176%2C47397%2C11828%2C38521%2C49509%2C25047%2C765%2C34224%2C107056%2C28016%2C48031%2C42305%2C49464%2C20913%2C67601%2C48311%2C98003%2C50261%2C11427%2C74887%2C83550%2C59744%2C14035%2C83992%2C5302%2C41584%2C23665%2C82752%2C35628%2C12890%2C83371%2C3331%2C46602%2C3959%2C31303%2C27173%2C51759%2C68519%2C57190%2C93537%2C4021%2C77407%2C69771%2C32813%2C34909%2C34038%2C87735%2C99784%2C74830%2C25318%2C58758%2C37830%2C36136%2C33308%2C37205%2C17004%2C50171%2C59525%2C35148%2C35908%2C4038%2C38264%2C48948%2C62466%2C43912%2C64194%2C90994%2C93381%2C28956%2C36391%2C40946%2C76643%2C87424%2C91073%2C47096%2C42365%2C103886%2C49482%2C62818%2C59271%2C74673%2C60662%2C62313%2C4075%2C10803%2C93383%2C23933%2C45619%2C43962%2C49342%2C39012%2C31074%2C36503%2C89153%2C105642%2C35247%2C23602%2C11081%2C48568%2C35587%2C79684%2C44702%2C48075%2C25531%2C48618%2C49556%2C40927%2C99783%2C34217%2C93161%2C57656%2C29759%2C72273%2C101465%2C9787%2C65113%2C96386%2C79686%2C38573%2C44886%2C43242%2C38831%2C10149%2C35097%2C32657%2C48017%2C33367%2C5796%2C24200%2C82050%2C12784%2C43227%2C67090%2C47698%2C12886%2C60635%2C20868%2C93449%2C29309%2C10174%2C32087%2C33951%2C15744%2C7922%2C1486%2C35360%2C35663%2C38566%2C1459%2C69927%2C74196%2C88366%2C48586%2C81072%2C21313%2C49711%2C32992%2C48999%2C64920%2C3978%2C44382%2C47442%2C65842%2C29451%2C58380%2C37310%2C38455%2C61797%2C91722%2C22994%2C22817%2C25486%2C87619%2C58289%2C74074%2C2233%2C34216%2C89077%2C48065%2C22409%2C281%2C87856%2C14128%2C21626%2C60610%2C31918%2C36111%2C34122%2C22773%2C102126%2C96917%2C22940%2C55371%2C56480%2C17894%2C20401%2C91260%2C62823%2C13950%2C104241%2C102009%2C102915%2C37208%2C37873%2C87870%2C75365%2C76203%2C13771%2C17954%2C32323%2C28665%2C95676%2C25409%2C21786%2C29397%2C34093%2C33912%2C78429%2C14239%2C100595%2C54283%2C13540%2C55767%2C88920%2C37161%2C34113%2C40773%2C36419%2C89017%2C32654%2C93099%2C22017%2C15662%2C68699%2C87688%2C97885%2C33966%2C16910%2C93097%2C7521%2C72796%2C79760%2C32793%2C1496%2C22374%2C63849%2C89150%2C51360%2C77914%2C90081%2C55826%2C1845%2C32887%2C498%2C33224%2C58252%2C60434%2C33023%2C101672%2C93555%2C19305%2C86845%2C74064%2C4675%2C1392%2C16347%2C48478%2C22900%2C53172%2C28283%2C33063%2C4657%2C30642%2C22642%2C22500%2C48310%2C32090%2C74406%2C48200%2C102164%2C1112%2C1026%2C29113%2C97642%2C58352%2C13040%2C13467%2C93315%2C31280%2C26912%2C71120%2C33926%2C512%2C68526%2C32884%2C32645%2C104804%2C33211%2C35103%2C28438%2C12599%2C13460%2C20956%2C22378%2C5575%2C500%2C34054%2C40237%2C41500%2C33448%2C54444%2C74401%2C41464%2C9902%2C19017%2C48012%2C28428%2C3392%2C3919%2C32917%2C43204%2C108254%2C10297%2C2780%2C6757%2C18832%2C2456%2C26044%2C5041%2C46584%2C44169%2C48968%2C1148%2C43470%2C91095%2C16750%2C6272%2C4041%2C57255%2C825%2C58134%2C65860%2C31127%2C3402%2C90686%2C91290%2C49738%2C38301%2C40171%2C13022%2C47210%2C84664%2C64173%2C55507%2C58225%2C1332%2C28499%2C224%5D&severities=%5B4%2C5%5D&tags=%5B%22uneven%2Fslanted%22%5D:1 Failed to load resource: the server responded with a status of 414 (Request-URI Too Long)
```

image

### PR DESCRIPTION
**Pull request by sidlak-c137**
Resolves #2584

Shortened the uri by converting the loadedLabels parameter to a body parameter. I wrote some "hacky" code to get around the `Redirect("anonSignUp?url=...")` as this function only ran GET requests. To get around this, I created a fake GET endpoint that auto-passes and reran the request manually.

##### Testing instructions
I am not sure how to test this as I do not have more than a few pages of labelled images on localhost. However, to test that my code does not affect the gallery:
1. Go to `/gallery`
2. Make sure images still load
3. Clear cookies and reload to make sure anonomous signup still works

### CODE REVIEW

**Comment by misaugstad** [comment]
>I wrote some "hacky" code to get around the `Redirect("anonSignUp?url=...")` as this function only ran GET requests. To get around this, I created a fake GET endpoint that auto-passes and reran the request manually.

Hmm. I don't think that doing that redirect is worth the hacky fix to be able to use it. I think that I'd rather just remove the fake endpoint and turn this into a POST request. Love the creative solution! But it's probably better to keep things simple in this case :grin:

**Comment by sidlak-c137** [comment]
@misaugstad I have simplified the code fix greatly by removing the redirect.

File: app/formats/json/LabelFormat.scala [hunk 1]
```diff
@@ -7,6 +7,7 @@ import play.api.libs.json._
 import play.api.libs.functional.syntax._
 
 object LabelFormat {
+  case class LoadedLabels(loaded_labels: String)
```
Comment (misaugstad) [inline app/formats/json/LabelFormat.scala:10]: Can you switch this up to read in a `Seq[Int]` instead of a String? You might not even need to add anything to the formats file, actually. I think that on the back end you can do `request.body.validate[Seq[Int]]` and on the front end I think you could just do
```
data: JSON.stringify(loadedLabels),
```

File: app/controllers/GalleryController.scala [hunk 2]
```diff
@@ -66,39 +81,46 @@ class GalleryController @Inject() (implicit val env: Environment[User, SessionAu
...
+          // If the user doesn't already have an anonymous ID,  will not do anything
+          case _ => Future.successful(
+            Ok(Json.obj("ok" -> "ok"))
+          )
+        }
+      }
+    )
+  }
 
+  def getLabelsBySeveritiesAndTagsPass() = UserAwareAction.async { implicit request =>
```
Comment (misaugstad) [inline app/controllers/GalleryController.scala:123]: I think you just forgot to delete this

File: app/controllers/GalleryController.scala [hunk 3]
```diff
@@ -3,14 +3,17 @@ package controllers
 import javax.inject.Inject
 import controllers.headers.ProvidesHeader
 import controllers.helper.GoogleMapsHelper
+import formats.json.LabelFormat._
 import models.user._
+import models.validation._
```
Comment (misaugstad) [inline app/controllers/GalleryController.scala:8]: Once you've finished with everything else, make sure to remove any imports you added but no longer need

File: app/controllers/GalleryController.scala [hunk 4]
```diff
@@ -33,27 +36,39 @@ class GalleryController @Inject() (implicit val env: Environment[User, SessionAu
...
+      }
+    )
+  }
 
-      // If the user doesn't already have an anonymous ID, sign them up and rerun.
-      case _ => Future.successful(
-        Redirect(s"/anonSignUp?url=/label/labelsByType?labelTypeId=" + labelTypeId + "&n=" + n + "&loadedLabels=" + loadedLabels)
-      )
-    }
+  def getLabelsByTypePass() = UserAwareAction.async { implicit request =>
```
Comment (misaugstad) [inline app/controllers/GalleryController.scala:70]: I think you just forgot to delete this

File: app/formats/json/LabelFormat.scala (hunk 1 above)
Comment (misaugstad) [reply app/formats/json/LabelFormat.scala:10]: After looking around a bit more, I have a better idea. Since we are already switching to a POST request of the label_ids, we should just put all of the metadata into the `data` field. So the data type would look something more like
```
case class GalleryLabelsRequest(labelTypeId: Int, n: Int, severities: Option[Seq[Int]], tags: Option[Seq[String]], loadedLabels: Seq[Int])
```

This way, we can actually combine the `getLabelsByType()` and `getLabelsBySeveritiesAndTags()` functions into one function that just behaves differently based on the input!

You could add it to `GalleryTaskSubmissionFormats.scala` instead of `LabelFormat.scala`, though I'd rename it to `GalleryFormats.scala` at that point as well.

Similarly, `fetchLabelsByType()` and `fetchLabelsBySeverityAndTags()` could probably be merged into one function. It looks like they are identical except for defining the URL.

**Review by misaugstad — CHANGES_REQUESTED** [review]
Thanks @sidlak-c137 I like this solution much better; much less hacky :) Switching to a POST request here actually makes it relatively straightforward to simplify a bunch of our code and remove duplicate code. You'll see what I'm talking about in the comments.

Let me know if any of that is unclear. It might take a bit of time, but I don't expect it to be too difficult to accomplish, and it'll make this code so much cleaner!!

**Comment by sidlak-c137** [comment]
@misaugstad I think I finished refactoring this code. Let me know if I missed anything!

**Review by misaugstad — APPROVED** [review]
I made a couple small changes to code style, but it looks great! Thanks for following up on this @sidlak-c137
