### PR TITLE
Fixed <#2115>: Fixed image popup location in validation

### LINKED ISSUE #2115: Example image popups in wrong location on validation
Here is what it looks like for me:
example-location-off-1
example-location-off-2
example-location-off-3
example-location-off-4

### PR DESCRIPTION
**Pull request by rpechuk**
Resolves #2115 

Moved the vertical placement of the popup into the same function that handles horizontal placement and fixed the vertical placement in order to make sure the popup is in the correct location.

### CODE REVIEW

File: public/javascripts/SVValidate/src/status/StatusExample.js [hunk 1]
```diff
@@ -57,12 +57,15 @@ function StatusExample (statusUI) {
     }
 
     /**
-     * Sets the horizontal position and height of the popup based on which picture was hovered over.
+     * Sets the horizontal position, vertical position, and height of the popup
+     * as well as the popup pointer basedon which picture was hovered over.
```
Comment (misaugstad) [inline public/javascripts/SVValidate/src/status/StatusExample.js:61]: Can this comment be made more concise so that it fits on one line (max 120 characters)?

File: public/javascripts/SVValidate/src/status/StatusExample.js [hunk 2]
```diff
@@ -57,12 +57,15 @@ function StatusExample (statusUI) {
...
      * @param id    ID name for the label example HTML element that the user hovered over.
      * @private
      */
     function _setPopupLocation (id) {
         // 1 = upper left, 2 = upper right, 3 = bottom left, 4 = bottom right
+
+        // Horizontal positioning
```
Comment (misaugstad) [inline public/javascripts/SVValidate/src/status/StatusExample.js:68]: Can you add a period to the end of this comment and the following comment, to adhere to the [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide)?

Comment (rpechuk) [reply public/javascripts/SVValidate/src/status/StatusExample.js:68]: Even though the rest of the comments don't have periods at the end?

Comment (misaugstad) [reply public/javascripts/SVValidate/src/status/StatusExample.js:68]: Yeah, we're slowly converting everything over to this method :sweat_smile: if you're feeling ambitious, you can feel free to edit the other comments to fit the style too :grin:
