### PR TITLE
Fixed neighborhood name commas breaking csv formatting

### LINKED ISSUE #3390: APIs not dealing with neighborhoods with commas in CSV format
##### Brief description of problem/feature
@devonsnyder brought to my attention that the data looked messed up in CSV format for some data she was getting from our API (pic below). The reason is that the neighborhood is called "Little Italy, UIC"; there is a comma in the field for a CSV (comma-separated value) file.

Screenshot from 2023-09-26 16-32-05

##### Steps to reproduce
Here's the API call that @devonsnyder used:
https://sidewalk-chicago.cs.washington.edu/v2/access/attributes?lat1=41.863085&lng1=-87.661878&lat2=41.874468&lng2=-87.646729&filetype=csv

##### Potential solution(s)
I believe that the standard when your data could contain a comma is to surround it in double quotes. From what I can tell, the only data in our APIs that could have commas are the "Neighborhood Name" columns in `/v2/access/attributes`, `/v2/access/attributesWithLabels`, and `/v2/access/score/neighborhoods`. Should be pretty easy to update!

### PR DESCRIPTION
**Pull request by davphan**
Resolves #3390

Neighborhood names containing commas would break the CSV file formatting, acting as an unintended delimiter. This PR adds double quotes around each instance of neighborhood names being referenced in CSV files, namely in these API calls:

- /v2/access/attributes
- /v2/access/attributesWithLabels
- /v2/access/score/neighborhoods

##### Before/After screenshots (if applicable)

Before:
image

After:
image

##### Testing instructions
1. Check the Label Map to find the coordinates of an area populated with labels. Choose a min/max lat and min/max long.
2. Use this URL to fetch the csv file from the API: 
 - `localhost:9000/v2/access/attributes?lat1=<x1>&lng1=<y1>&lat2=<x2>&lng2=<y2>&filetype=csv`
 - `localhost:9000/v2/access/attributesWithLabels?lat1=<x1>&lng1=<y1>&lat2=<x2>&lng2=<y2>&filetype=csv`
 - `localhost:9000/v2/access/score/neighborhoods?lat1=<x1>&lng1=<y1>&lat2=<x2>&lng2=<y2>&filetype=csv`
 a. If you have coordinates with a known neighborhood with commas in the name, use that instead! (i.e. https://sidewalk-chicago.cs.washington.edu/v2/access/attributes?lat1=41.863085&lng1=-87.661878&lat2=41.874468&lng2=-87.646729&filetype=csv on the Chicago database)
3. View the downloaded CSV. Make sure the Neighborhood Name column is correct and that subsequent columns are in the right spot
 
##### Things to check before submitting the PR 

- [x] I've written a descriptive PR title. 
- [x] I've added/updated comments for large or confusing blocks of code.
- [x] I've included before/after screenshots above.

### CODE REVIEW

File: app/controllers/ProjectSidewalkAPIController.scala [hunk 1]
```diff
@@ -147,7 +147,9 @@ class ProjectSidewalkAPIController @Inject()(implicit val env: Environment[User,
       writer.println(header)
       // Write each row in the CSV.
       for (current <- GlobalAttributeTable.getGlobalAttributesWithLabelsInBoundingBox(minLat, minLng, maxLat, maxLng, severity)) {
-        writer.println(current.attributesToArray.mkString(","))
+        val rowArr: Array[String] = current.attributesToArray
+        rowArr(6) = "\"" + rowArr(6) + "\""
```
Comment (misaugstad) [inline app/controllers/ProjectSidewalkAPIController.scala:151]: Let's try our best not to rely on knowing which index in the array to use for the neighborhood name. Is there a more programmatic way that we can do it, like adding the quotes in the `attributesToArray` method?

**Comment by davphan** [comment]
@misaugstad Adjusted the commit to add quotes through the attributesToArray methods, everything's been tested again the same way!

**Review by misaugstad — APPROVED** [review]
Perfect, thank you!
