### PR TITLE
Resolves Zooming Issues with Context Menu Open

### LINKED ISSUE #623: Shift-Z zooms-in when label menu open
When the label/context menu is open (as in picture below), Shift-Z zooms *in* instead of out. When the menu is not open, it works as expected.

Was able to reproduce this on both Firefox and Chrome.

sidewalk-label_menu

### PR DESCRIPTION
**Pull request by sagec108**
Resolves #623. Zooming in should now work properly while the context menu is open. Zooming using the keyboard closes the menu first and then zooms.

### CODE REVIEW

File: public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js [hunk 1]
```diff
@@ -62,7 +62,13 @@ function Keyboard (svl, canvas, contextMenu, googleMap, ribbon, zoomControl) {
     this._documentKeyDown = function (e) {
         // The callback method that is triggered with a keyUp event.
         if (contextMenu.isOpen()) {
-            return;
+            if (e.keyCode == 16){
+                status.shiftDown = true;
+            }//only permits shift key value change when ctxt menu open
+            //kept separate from switch statement in elseif
+            if (e.keyCode == 187 || e.keyCode == 189){
```
Comment (manaswis) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: Could you add a comment indicating the actual keys for 187 and 189?

Comment (sagec108) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: I added some comments. This was part of my attempt to disable +/- zoom, but it didn't work very well.

Comment (manaswis) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: Cool, thanks! Do a git pull before pushing it.

**Comment by manaswis** [comment]
Also, could you look into handling this behavior:

When the mouse is hovered over the label, and then we zoom-in, it looks like this:

image

The zoom-out is similar but reverse:

image

Ideal location:

image

Maybe just hide it when the zoom-in/out is happening.

File: public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js [hunk 2]
```diff
@@ -61,8 +61,18 @@ function Keyboard (svl, canvas, contextMenu, googleMap, ribbon, zoomControl) {
...
+            if (contextMenu.isOpen()) {
+                if (e.keyCode == 16) {
+                    status.shiftDown = true;
+                }//only permits shift key value change when ctxt menu open
+                //kept separate from switch statement in elseif
+                if (e.keyCode == 187 || e.keyCode == 189) {
+                    svl.contextMenu.hide();
+                }
+                //equal button || - button
+                return;
```
Comment (manaswis) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: return not needed here since its the last statement of the block

File: public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js [hunk 3]
```diff
@@ -61,8 +61,18 @@ function Keyboard (svl, canvas, contextMenu, googleMap, ribbon, zoomControl) {
...
+        if (!status.focusOnTextField) {
+            if (contextMenu.isOpen()) {
+                if (e.keyCode == 16) {
+                    status.shiftDown = true;
+                }//only permits shift key value change when ctxt menu open
+                //kept separate from switch statement in elseif
+                if (e.keyCode == 187 || e.keyCode == 189) {
+                    svl.contextMenu.hide();
+                }
+                //equal button || - button
```
Comment (manaswis) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: Also, could you update the comments to be placed above the corresponding code here and in the future? It would be good for consistency since all the comments are done in this way in the codebase.

File: public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js [hunk 4]
```diff
@@ -61,8 +61,18 @@ function Keyboard (svl, canvas, contextMenu, googleMap, ribbon, zoomControl) {
      */
     this._documentKeyDown = function (e) {
         // The callback method that is triggered with a keyUp event.
-        if (contextMenu.isOpen()) {
-            return;
+        if (!status.focusOnTextField) {
```
Comment (manaswis) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: This condition is the same as the else if condition. Should be merged into one.

Comment (sagec108) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: Fixed in my latest commit, this was caused by some kind of code conflict.

File: public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js (hunk 2 above)
Comment (sagec108) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: Fixed in latest commit

File: public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js (hunk 3 above)
Comment (sagec108) [inline public/javascripts/SVLabel/src/SVLabel/keyboard/Keyboard.js]: Fixed in latest commit

**Comment by sagec108** [comment]
For now, I will make pressing the +/- buttons to always hide the context menu (which avoids breaking panning and context menu). This is a temporary fix, as it means users can no longer type in "-" or "=" signs into the description box.

**Comment by jonfroehlich** [comment]
I don't understand the problem with the +/- keypresses. Can you explain this to me? Do we have this documented anywhere as a github issue?

**Comment by sagec108** [comment]
The street view api seems to handle the "+" and "-" button presses by zooming in. This is a functionality not included in the tutorial and causes the issues noted in issue #678. I haven't found a good solution yet so I've patched it by simply hiding the menu whenever the user presses either button.

**Comment by manaswis** [comment]
@sagec108 Did you look into this - https://github.com/ProjectSidewalk/SidewalkWebpage/pull/650#issuecomment-309219158

**Comment by sagec108** [comment]
I'm looking into it but there isn't a clear way to hide the label tag whenever the user zooms. Maybe if the user's cursor is on the label, disable zooming?

**Comment by manaswis** [comment]
How does it work currently? The label tag shows when the mouse is hovered over the label and disappears when mouse leaves. So there should be some mechanism in place to hide it. Maybe use that?

**Comment by sagec108** [comment]
I fixed it so that whenever the user zooms the tag and delete icon are hidden (both would become displaced if the user zoomed while hovering over a label before).
