### PR TITLE
Restored Admin Playback Page

### LINKED ISSUE #595: Admin Playback Tool page is currently broken
The page that allows us to see how the audit has been done by the user is broken. It doesn't show the top-down full scale map that used to show up to see the applied labels as it is being applied. Only the GSV review window is visible. Following is the screenshot:

image

Adding it to the summer tasks.

### PR DESCRIPTION
**Pull request by sagec108**
Resolves #595. Besides changing some formatting (e.g separating html elements into bootstrap columns) and making it so that RHS column is not on top of the map, I kept the page the same. 

Adding actual playback functionality should be handled in #391. As mentioned in #391 , implementing playback functionality is really difficult (task playing is not a video file, would have to create player from scratch). I looked into using the bootstrap slider class, but I ran into some issues integrating animation of the slider into the page.

Here is a screenshot:
image

### CODE REVIEW

File: app/views/admin/task.scala.html [hunk 1]
```diff
@@ -6,17 +6,27 @@
...
                     <div id="timeline-active"></div>
                     <div id="timeline-handle"></div>
                 </div>
+                <div id="eventsholder"></div>
             </div>
         </div>
     </div>
+    <script type="text/javascript" src='@routes.Assets.at("javascripts/lib/bootstrap-3.3.5/js/bootstrap-slider.min.js")'></script>
+    <link href='@routes.Assets.at("javascripts/lib/bootstrap-3.3.5/css/bootstrap-slider.min.css")' rel="stylesheet"/>
+    <script>
```
Comment (manaswis) [inline app/views/admin/task.scala.html]: Any reason why the script block was moved up?

Comment (sagec108) [inline app/views/admin/task.scala.html]: I was fiddling around with integrating the bootstrap slider to replace the css slider we currently have on the playback page. I think I shifted around some javascripts in the process and forgot to revert those changes.

Comment (manaswis) [inline app/views/admin/task.scala.html]: Okay, cool. Could you update it?
