### PR TITLE
2863 Incorrect Percent Mapped

### LINKED ISSUE #2863: incorrect % of Chicago mapped
The Chicago deployment landing page says 30% of Chicago has been mapped, but it is much lower. Am thinking this is related to how much we've opened up right? Is there a way to revise this percentage so people who visit the site don't get the wrong idea? Like call it % of sidewalks opened in Chicago area? or recalculate based on total miles of road?
Thanks,
Yochai

### PR DESCRIPTION
**Pull request by palbirmin**
Resolves  #2863 

Created a config for whether or not a city has been open. If the city isn't open, it will display the text "X% of target area. 

##### Before/After screenshots (if applicable)
**Before** 
I have used the testing site to show the text:
image
**After:**
image

##### Testing instructions
1.  Simply run the website and check each City's display text. 
##### Things to check before submitting the PR 
- I've written a descriptive PR title.
- I've included before/after screenshots above.
- I've asked for and included translations for any user-facing text that was added or modified.
- I've tested on mobile (only needed for the validation page).

### CODE REVIEW

**Review by misaugstad — CHANGES_REQUESTED** [review]
@palbirmin I've added a few comments throughout the code on the PR with things to touch up before we merge the PR! Great job getting the main functionality done! We just have a few things to fix and polish up :)

File: app/views/index.scala.html [hunk 1]
```diff
@@ -154,10 +158,14 @@
             </a>
         </div>
         <script language="javascript">
-            if (@("%.0f".format(StreetEdgePriorityTable.streetDistanceCompletionRateUsingPriority * 100)) < 100) {
-                document.getElementById('conditional-text').innerHTML = "@Messages("landing.stats.content.unfinished", "%,.0f".format(auditedDistance), cityName, stateAbbreviation, "%.1f".format(StreetEdgePriorityTable.streetDistanceCompletionRateUsingPriority * 100))";
-            } else {
-                document.getElementById('conditional-text').innerHTML = "@Messages("landing.stats.content.finished", "%,.0f".format(auditedDistance), cityName, stateAbbreviation)";
+	    if (("@(Play.configuration.getString("city-params.open-status." + cityId).get)" === "partially")&&(@("%.0f".format(StreetEdgePriorityTable.streetDistanceCompletionRateUsingPriority * 100)) >= 100)) {
```
Comment (misaugstad) [inline app/views/index.scala.html:161]: You have a lot of extra parentheses throughout this file. You added parens around each condition in the `if`, which isn't necessary, and you also added parens around your call to `Play.configuration` which isn't necessary.

With template Scala, you only need parens directly after the `@` symbol if it's more than just a call to a single function (like when we use `@("%.0f".format( ... ))`. But just calling `@Play.configuration.getString(...)` works fine.

So this line
```
if (("@(Play.configuration.getString(...).get)" === "partially")&&(@("%.0f".format(...)) >= 100)) {
```

Should probably look more like this
```
if ("@Play.configuration.getString(...).get" === "partially" && @("%.0f".format(...)) >= 100) {
```

**Review by misaugstad — CHANGES_REQUESTED** [review]
In addition to the comments in the code, I would also ask you to read through our [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide). The style issues I noticed are
1. Missing spaces around your `&&`
2. Using tabs instead of spaces. This can mess up what indentation looks like in another person's IDE, so we want to keep spaces everywhere. There's a pic below of what that section looks like in my editor. Please change the settings in your IDE to use spaces by default, and go through all the lines that you added/changed to make sure that the indentation now looks correct and uses spaces :)
Screenshot from 2022-05-18 11-48-49

But I wouldn't worry about the line length requirement in the style guide in this particular case.

**Review by misaugstad — APPROVED** [review]
Looks much better :) Thanks for all the iteration @palbirmin. And congrats on your first PR!!
