### PR TITLE
Fixed panning on both Safari and Microsoft Edge

### LINKED ISSUE #614: Panning Broken for Certain Browsers
A user reported:

image

This could be a previously described Issue using Safari (I think here https://github.com/ProjectSidewalk/SidewalkWebpage/issues/577). 

@manaswis: do we log a user's web browser and other system information (device info, browser version, resolution, etc.) so that we can go back and check into this more deeply?

### PR DESCRIPTION
**Pull request by sagec108**
Found an issue in accessing a scaling factor while calculating the change in mouse coordinates while panning. By not rounding the value used to access the scaling factor, the code would fail to access the appropriate scaling factor and prevent panning. Resolves #614. I also fixed the zooming bug for edge users as referenced in #623.

### CODE REVIEW

**Comment by manaswis** [comment]
Not related to this issue, but while testing this PR I noticed that, in Safari, after the labels are applied, the icon imagery disappears:

image

This issue is investigated in depth in the closed issue #316. Soheil had noted that the icons show up on the deployed server and not on the local server. So we should keep a check on that when testing it on the server.

**Comment by jonfroehlich** [comment]
Should reopen that issue or create new issue?

**Comment by manaswis** [comment]
New issue would be good - things to check for relaunch testing. I'll create one.

**Comment by manaswis** [comment]
Created #687 to track things to test such as these.

File: public/javascripts/SVLabel/src/SVLabel/zoom/ZoomControl.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ function ZoomControl (canvas, mapService, tracker, uiZoomControl) {
         },
         status = {
             disableZoomIn: false,
-            disableZoomOut: false
+            disableZoomOut: true
```
Comment (manaswis) [inline public/javascripts/SVLabel/src/SVLabel/zoom/ZoomControl.js]: Could you explain what you did here?

Comment (sagec108) [inline public/javascripts/SVLabel/src/SVLabel/zoom/ZoomControl.js]: By default the user should not be able to zoom out without first zooming in (at least this is the behavior of our tool on Chrome). This behavior is not replicated in Edge. The ZoomOut button can be clicked, and clicking on it will actually zoom in instead of zoom out.  To fix this, I disable zooming out until the user zooms in. upon which zooming out is enabled.

**Comment by jonfroehlich** [comment]
> Created #687 to track things to test such as these.

I'm not sure how I feel about these 'supersized' issues that include a long list of issues within them. Will have to see how it works out but I feel like creating an individual issue for this (rather than adding it to a list of issues in one Issue) is more consistent with our issue handling thus far...

**Comment by manaswis** [comment]
@jonfroehlich I wanted to have a comprehensive consolidated list of changes made for reference when we do thorough testing. This will help in testing for specific changes and look for any side-effects on other elements of the tool. 

We will definitely create an issue when we find a bug or some misbehavior. The list will help in going back to the specific change made in a PR. I created a label 'Relaunch Testing' to be applied to these issues (for future reference) and to properly segregate things.

**Comment by jonfroehlich** [comment]
Sounds good. If it works out, we can use a similar paradigm in future releases.
