### PR TITLE
Neighborhood hover not working on our maps in Firefox #3777

### LINKED ISSUE #3777: Neighborhood hover not working on our maps in Firefox
##### Brief description of problem/feature
When trying to move your mouse onto the tooltip, it goes away. This is happening on landing page, user dashboard, etc.

##### System info (OS, browser, city, and local/prod/test)
Happening on Firefox. Works well on Chrome. Haven't tested on Safari.

### PR DESCRIPTION
**Pull request by heonjwa**
Resolves #3777 

Configured tooltopTimout variable to handle flickering on toolbox when hovered by adding slight delay when removing tool tip which gives the user time to move their mouse onto the tooltip.

##### Before/After screenshots (if applicable)

https://github.com/user-attachments/assets/4bb58cc7-68e9-4445-97af-ea614b63a8fa

https://github.com/user-attachments/assets/9bdae156-b64e-4f8d-bf05-353244bf01c4

##### Testing instructions
1. Open up firefox and hover over label map and check whether there is flickering.

##### Things to check before submitting the PR 

- [x] I've written a descriptive PR title. 
- [x] I've added/updated comments for large or confusing blocks of code.
- [x] I've included before/after screenshots above.
- [x] I've asked for and included translations for any user facing text that was added or modified.
- [x] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how (or if you need to update the logging), ask Mikey. Then make sure the documentation on [this wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Descriptions-of-Logged-Events) is up to date for the logs you added/updated.
- [ ] I've tested on mobile (only needed for validation page).

### CODE REVIEW

File: public/javascripts/PSMap/AddNeighborhoodsToMap.js [hunk 1]
```diff
@@ -168,14 +170,22 @@ function AddNeighborhoodsToMap(map, neighborhoodGeoJSON, completionRates, labelC
                 const regionCenter = turf.centerOfMass(currRegion).geometry.coordinates;
                 neighborhoodTooltip.setLngLat({ lng: regionCenter[0], lat: regionCenter[1] }).addTo(map);
 
-                // Add listeners to popup so the popup closes when the mouse leaves the popup area.
-                neighborhoodTooltip._content.onmouseout = function (e) {
-                    if (!e.toElement || !e.toElement.closest('.mapboxgl-popup')) {
+                // Clear timeout when entering new toolTip
+                neighborhoodTooltip._content.onmouseenter = function () {
+                    if (tooltipTimeout) {
+                        clearTimeout(tooltipTimeout); // Clear the timeout if the mouse enters the tooltip
```
Comment (misaugstad) [inline public/javascripts/PSMap/AddNeighborhoodsToMap.js:176]: And when we call `clearTimeout` we're actually never unsetting the `tooltipTimeout` variable. So after the first tooltip opens, `tooltipTimeout` will never be falsey. Which is fine, because we can keep trying to clear the timeout for a timer that's already been cleared. Similarly, we can keep calling `clearTimeout` on `undefined`! So maybe let's just not bother with checking if `tooltipTimeout` is defined to simplify things even more:
```
                // Clear timeout when entering a tooltip.
                neighborhoodTooltip._content.onmouseenter = function () { clearTimeout(tooltipTimeout); };
```

And we can simplify in the same way throughout

**Review by misaugstad — CHANGES_REQUESTED** [review]
Seems to be working nicely! I tested on Chrome and Firefox for now. Are you using a Mac? If so, have you checked that it's working on Safari as well?

I also added a couple of comments throughout the code to address. Nothing major!

**Comment by heonjwa** [comment]
Works on Safari!

**Comment by heonjwa** [comment]
Updated the changes you mentioned and committed

File: public/javascripts/PSMap/AddNeighborhoodsToMap.js [hunk 2]
```diff
@@ -168,14 +170,22 @@ function AddNeighborhoodsToMap(map, neighborhoodGeoJSON, completionRates, labelC
                 const regionCenter = turf.centerOfMass(currRegion).geometry.coordinates;
                 neighborhoodTooltip.setLngLat({ lng: regionCenter[0], lat: regionCenter[1] }).addTo(map);
 
-                // Add listeners to popup so the popup closes when the mouse leaves the popup area.
-                neighborhoodTooltip._content.onmouseout = function (e) {
-                    if (!e.toElement || !e.toElement.closest('.mapboxgl-popup')) {
+                // Clear timeout when entering new toolTip
```
[the remark this answers is not in the document]
Comment (misaugstad) [reply public/javascripts/PSMap/AddNeighborhoodsToMap.js]: Note that I only added a specific comment on here for the first comment I saw that didn't meet style guide. You just changed this one but none of your other comments have been changed! I find it helpful to go over to the "Files changed" tab of the PR yourself so that you can see what I'm seeing to head off any feedback I might be sending your way!

File: public/javascripts/PSMap/AddNeighborhoodsToMap.js (hunk 1 above)
Comment (misaugstad) [reply public/javascripts/PSMap/AddNeighborhoodsToMap.js]: Same sort of situation happens later in the code that still needs to be redone:
```
        map.on('mouseenter', NEIGHBORHOOD_LAYER_NAME, () => {
            if (tooltipTimeout) {
                clearTimeout(tooltipTimeout);
            }
```

**Review by misaugstad — APPROVED** [review]
Looking good now, thanks for the fix!
